networks:
  projetos-vps:
    external: true

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:
    driver: local

services:
  cloudflaretunnel:
    image: cloudflare/cloudflared:2025.7.0
    container_name: cloudflaretunnel
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      - projetos-vps

  postgres:
    image: postgres:15-alpine
    container_name: postgres15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projetos-vps
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - projetos-vps
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - projetos-vps

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    networks:
      - projetos-vps

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - "8086:80"
    volumes:
      - /home/henrique:/srv
      - /home/henrique/.filebrowser/filebrowser.db:/database.db
      - /home/henrique/.filebrowser/settings.json:/config/settings.json
    networks:
      - projetos-vps
    security_opt:
      - no-new-privileges:true
